FLAGS = -Wall -lm

lab1: lab1.c padre.o hijo.o funciones.o
	gcc $(FLAGS) -o lab1 lab1.c padre.o hijo.o funciones.o

padre.o: padre.c
	gcc -c $(FLAGS) padre.c

hijo.o: hijo.c
	gcc -c $(FLAGS) hijo.c

funciones.o: funciones.c
	gcc -c $(FLAGS) funciones.c

clear:
	rm -f *.o lab1 hijo.o padre.o intermedio.csv funciones.o hijo1.txt hijo2.txt hijo0.txt hijo3.txt hijo4.txt salida.txt hijo5.txt hijo6.txt hijo7.txt hijo8.txt hijo9.txt hijo10.txt hijo11.txt hijo12.txt hijo13.txt hijo14.txt hijo15.txt hijo16.txt hijo17.txt hijo18.txt hijo19.txt hijo20.txt hijo21.txt hijo22.txt hijo23.txt hijo24.txt hijo25.txt hijo26.txt          
